### ISSUE TITLE
in finetune.py 117 Why "-i"??

### ISSUE THREAD

**Issue by toutuo** [jacobgil/pytorch-pruning#32]
![image](https://user-images.githubusercontent.com/31120686/59988819-10dd8500-966f-11e9-8f52-6f0a12360887.png)
Can anybody explain that? Thank you very much.

**Comment by jacobgil** [comment]
The way it is written, it removes filters chosen for pruning, one after another, in a sequential way.
After the first filter in a layer is pruned, the index of the next filter that needs to be pruned changes, because there is one less filter left.
for example, lets say we need to prune filters 3,10 in some layer.
After pruning filter #3, the layer is smaller, and the index of previous filter #10 is now #9.

Ideally the filters would be removed all at once, that would be a better way of writing this.

**Comment by toutuo** [comment]
Thank you very much, it turned out to be like this. I just didn’t understand this point. Thanks again.






At 2019-06-24 12:55:56, "Jacob Gildenblat" <notifications@github.com> wrote:


The way it is written, it removes filters chosen for pruning, one after another, in a sequential way.
After the first filter in a layer is pruned, the index of the next filter that needs to be pruned changes, because there is one less filter left.
for example, lets say we need to prune filters 3,10 in some layer.
After pruning filter #3, the layer is smaller, and the index of previous filter #10 is now #9.

Ideally the filters would be removed all at once, that would be a better way of writing this.
